spring:
  application:
    name: get-offer-batch
  baseurl: ENC(Hfr385kYpf0UVqqBfAe29hrGl4MBjgfa7YXfKg48uYw=)
  batch:
    job:
      name: startAuctionJob
      enabled: true
    jdbc:
      initialize-schema: always
  data:
    web:
      pageable:
        default-page-size: 30
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(uKelITbJd52jwMV9Mxa8Ghri9Vgyu1c2nLvSMP44vsfgbjNCFnm4QKvMji8F9Qze1TdaYQ3TA1ZlAFmBmFco1zmdSljsIr8C)
    username: get-offer-admin
    password: ENC(VmpS4S+sh6W685dx4xoN1UfClvfTg0/5)
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
jasypt:
  encryptor:
    bean: jasyptStringEncryptor   # java 빈 이름
    algorithm: PBEWithMD5AndDES   # 사용 알고리즘
    pool-size: 2    # 암호화 요청을 담을 pool 크기 설정 (2 권장)
    string-output-type: base64    # 암호화 이후 받을 타입
    key-obtention-iterations: 1000    # 암호화를 수행할 반복할 해시 횟수
    password: ${JASYPT_KEY}
management:
  info:
    java:
      enabled: true
    os:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,beans,conditions, httptrace, metrics
        exclude: threaddump, heapdump