name: CI/CD for Spring Boot with Docker Compose

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # 1. GitHub Repository의 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Gradle로 Spring Boot 애플리케이션 빌드
      - name: Build Spring Boot application
        env:
          JASYPT_KEY: ${{ secrets.JASYPT_KEY }}
        run: |
          ./gradlew clean build

      # 3. Docker 로그인
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 4. Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      # 5. 배포 서버에 Docker Compose로 컨테이너 갱신
      - name: Deploy with Docker Compose
        uses: applyboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}
          port: 22
          script: |
            docker-compose pull
            docker-compose up -d
